### ISSUE TITLE
[Bug] `nidaqmx` causes asyncio warnings on Python >= 3.8

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi-iqo-modules#4] opened 2021-11-16 10:34 UTC
### Version

current main

### What is affected by the bug?

- Windows 10
- Miniconda with Python 3.8.12

A warning from `asyncio` will show if you close qudi.

### When does the bug occur?

Everytime you import `nidaqmx` in any module and then close qudi.
A warning from `asyncio` will show.

### How do we replicate the issue?

1. Start qudi
2. Activate a module that imports `nidaqmx`, e.g. a NI hardware module
3. Quit qudi

### Expected behavior

Not show a warning and possibly not use `nidaqmx` since it is not maintained.

### Relevant log output

```shell
C:\Software\Miniconda3\envs\qudi\lib\asyncio\base_events.py:654: ResourceWarning: unclosed event loop <ProactorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
```

### Additional Comments

Starting with Python 3.8 the `asyncio` package uses a different default event loop (namely `ProactorEventLoop`).

Apart from that `nidaqmx` has not released anything since 2017 and we should seriously consider moving back to `PyDAQmx`. These problems will only get worse in the future with newer Python versions.

### Contact Details

tomek.qudi@gmail.com

**Comment by LukePiewalker** [comment] 2022-03-11 22:05
Actually, they came back to live at nidaqmx. They were some new releases last month. Should we give it a try? 🤔

**Comment by LukePiewalker** [comment] 2022-03-14 09:47
Just quickly installed the version 0.6.1, but the above mentioned error still occurs.

**Comment by LukePiewalker** [comment] 2022-11-28 11:39
Since this warning is not occuring anymore for me anymore maybe we can close this issue?

 However I'm kinda confused: The version of nidaqmx currently installed on my setup is 0.5.7 ... :confused: And apparently I tested with 0.6.1 back then ...

Now installing 0.6.4 does also not reproduce the behavior for me.

**Comment by Neverhorst** [comment] 2022-11-29 11:34
I would suspect `conda` vs. `PyPI`

**Comment by timoML** [comment] 2024-01-29 11:13
@kay-jahnke 
Is there anything new on this warning? Otherwise, we would close the issue as it seems fixed from our side.

**Comment by kay-jahnke** [comment] 2024-02-01 10:35
I have not been working with this qudi problem on hardware for a while. So I can't say anything about it.
I will close it and it can be reopened, if someone else encounters the problem.

**Closed by kay-jahnke** 2024-02-01 10:35 UTC
Labels: bug
